// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jenbtymphmckvzypeasm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbmJ0eW1waG1ja3Z6eXBlYXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MzU2MDUsImV4cCI6MjA4MDAxMTYwNX0.ldwMecKO6DjLa3EwYehHQp_fiWAIMwdFbSQAIj23qH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});